# Generated by Django 3.2.25 on 2026-08-24 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_profile_gamification(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    ProfileGamification = apps.get_model('judge', 'ProfileGamification')
    ProfileGamification.objects.bulk_create([
        ProfileGamification(profile_id=profile_id)
        for profile_id in Profile.objects.values_list('id', flat=True).iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0042_align_contest_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tier', models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=10, verbose_name='source tier')),
                ('target_tier', models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=10, verbose_name='target tier')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='unlocked at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'promotion attempt',
                'verbose_name_plural': 'promotion attempts',
                'ordering': ('-unlocked_at',),
            },
        ),
        migrations.CreateModel(
            name='PromotionExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('source_tier', models.CharField(choices=[('bronze', 'Bronze to Gold'), ('gold', 'Gold to Diamond')], db_index=True, max_length=10, verbose_name='source tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'promotion exam',
                'verbose_name_plural': 'promotion exams',
                'ordering': ('source_tier', '-is_active', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='promotion_order',
            field=models.PositiveIntegerField(default=0, verbose_name='promotion problem order'),
        ),
        migrations.CreateModel(
            name='PromotionAttemptProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_problems', to='judge.promotionattempt')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='judge.problem')),
            ],
            options={
                'verbose_name': 'promotion attempt problem',
                'verbose_name_plural': 'promotion attempt problems',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='promotionattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='judge.promotionexam', verbose_name='promotion exam'),
        ),
        migrations.AddField(
            model_name='promotionattempt',
            name='problems',
            field=models.ManyToManyField(related_name='_judge_promotionattempt_problems_+', through='judge.PromotionAttemptProblem', to='judge.Problem'),
        ),
        migrations.AddField(
            model_name='promotionattempt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_attempts', to='judge.profile', verbose_name='profile'),
        ),
        migrations.CreateModel(
            name='ProfileGamification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('diamond', 'Diamond')], db_index=True, default='bronze', max_length=10, verbose_name='current tier')),
                ('tier_updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tier updated at')),
                ('weighted_score', models.PositiveIntegerField(db_index=True, default=0, verbose_name='weighted solve score')),
                ('bronze_solved', models.PositiveIntegerField(default=0, verbose_name='bronze solved')),
                ('gold_solved', models.PositiveIntegerField(default=0, verbose_name='gold solved')),
                ('diamond_solved', models.PositiveIntegerField(default=0, verbose_name='diamond solved')),
                ('score_updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='score updated at')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='judge.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile gamification',
                'verbose_name_plural': 'profile gamification',
                'ordering': ('-weighted_score', '-diamond_solved', '-gold_solved', '-bronze_solved', 'profile_id'),
            },
        ),
        migrations.CreateModel(
            name='DifficultyCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('diamond', 'Diamond')], db_index=True, max_length=10, verbose_name='tier')),
                ('required_solve_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='required solve count')),
                ('ranking_weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ranking weight')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='difficulty_clusters', to='judge.problemtype', verbose_name='problem type')),
            ],
            options={
                'verbose_name': 'difficulty cluster',
                'verbose_name_plural': 'difficulty clusters',
                'ordering': ('tier', 'order', 'problem_type__full_name'),
            },
        ),
        migrations.RunPython(create_profile_gamification, migrations.RunPython.noop),
        migrations.AddField(
            model_name='problem',
            name='gamification_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='judge.difficultycluster', verbose_name='gamification cluster'),
        ),
        migrations.AddField(
            model_name='problem',
            name='promotion_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='judge.promotionexam', verbose_name='promotion exam'),
        ),
        migrations.AddConstraint(
            model_name='promotionattemptproblem',
            constraint=models.UniqueConstraint(fields=('attempt', 'problem'), name='unique_attempt_snapshot_problem'),
        ),
        migrations.AddConstraint(
            model_name='promotionattempt',
            constraint=models.UniqueConstraint(fields=('profile', 'source_tier'), name='unique_profile_source_tier_attempt'),
        ),
        migrations.AddConstraint(
            model_name='difficultycluster',
            constraint=models.UniqueConstraint(fields=('tier', 'problem_type'), name='unique_tier_problem_type_cluster'),
        ),
        migrations.AddConstraint(
            model_name='difficultycluster',
            constraint=models.CheckConstraint(check=models.Q(('required_solve_count__gte', 1)), name='positive_cluster_required_solves'),
        ),
        migrations.AddConstraint(
            model_name='difficultycluster',
            constraint=models.CheckConstraint(check=models.Q(('ranking_weight__gte', 1)), name='positive_cluster_ranking_weight'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(check=models.Q(('gamification_cluster__isnull', True), ('promotion_exam__isnull', True), _connector='OR'), name='exclusive_problem_gamification_role'),
        ),
    ]
