# Generated by Django 3.2.25 on 2026-08-24 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0043_gamification_tiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficultycluster',
            options={'ordering': ('tier', 'order', 'problem_type__full_name'), 'verbose_name': '난이도 클러스터', 'verbose_name_plural': '난이도 클러스터'},
        ),
        migrations.AlterModelOptions(
            name='profilegamification',
            options={'ordering': ('-weighted_score', '-diamond_solved', '-gold_solved', '-bronze_solved', 'profile_id'), 'verbose_name': '사용자 티어', 'verbose_name_plural': '사용자 티어'},
        ),
        migrations.AlterModelOptions(
            name='promotionattempt',
            options={'ordering': ('-unlocked_at',), 'verbose_name': '승급 기록', 'verbose_name_plural': '승급 기록'},
        ),
        migrations.AlterModelOptions(
            name='promotionattemptproblem',
            options={'ordering': ('order', 'id'), 'verbose_name': '승급전 문제 스냅샷', 'verbose_name_plural': '승급전 문제 스냅샷'},
        ),
        migrations.AlterModelOptions(
            name='promotionexam',
            options={'ordering': ('source_tier', '-is_active', '-created_at'), 'verbose_name': '승급전', 'verbose_name_plural': '승급전'},
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='표시 순서'),
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='difficulty_clusters', to='judge.problemtype', verbose_name='문제 유형'),
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='ranking_weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='랭킹 가중치'),
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='required_solve_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='승급 기준 풀이 수'),
        ),
        migrations.AlterField(
            model_name='difficultycluster',
            name='tier',
            field=models.CharField(choices=[('bronze', '브론즈'), ('gold', '골드'), ('diamond', '다이아몬드')], db_index=True, max_length=10, verbose_name='티어'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='gamification_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='judge.difficultycluster', verbose_name='난이도 클러스터'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='promotion_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='judge.promotionexam', verbose_name='승급전'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='promotion_order',
            field=models.PositiveIntegerField(default=0, verbose_name='승급전 문제 순서'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='bronze_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='브론즈 풀이 수'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='current_tier',
            field=models.CharField(choices=[('bronze', '브론즈'), ('gold', '골드'), ('diamond', '다이아몬드')], db_index=True, default='bronze', max_length=10, verbose_name='현재 티어'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='diamond_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='다이아몬드 풀이 수'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='gold_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='골드 풀이 수'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='judge.profile', verbose_name='사용자 프로필'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='score_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='점수 갱신 시각'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='tier_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='티어 변경 시각'),
        ),
        migrations.AlterField(
            model_name='profilegamification',
            name='weighted_score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='가중 점수'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료 시각'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='judge.promotionexam', verbose_name='승급전'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_attempts', to='judge.profile', verbose_name='사용자 프로필'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='source_tier',
            field=models.CharField(choices=[('bronze', '브론즈'), ('gold', '골드'), ('diamond', '다이아몬드')], max_length=10, verbose_name='출발 티어'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='target_tier',
            field=models.CharField(choices=[('bronze', '브론즈'), ('gold', '골드'), ('diamond', '다이아몬드')], max_length=10, verbose_name='목표 티어'),
        ),
        migrations.AlterField(
            model_name='promotionattempt',
            name='unlocked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='해금 시각'),
        ),
        migrations.AlterField(
            model_name='promotionattemptproblem',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_problems', to='judge.promotionattempt', verbose_name='승급 기록'),
        ),
        migrations.AlterField(
            model_name='promotionattemptproblem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='표시 순서'),
        ),
        migrations.AlterField(
            model_name='promotionattemptproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='judge.problem', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='promotionexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시각'),
        ),
        migrations.AlterField(
            model_name='promotionexam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='promotionexam',
            name='source_tier',
            field=models.CharField(choices=[('bronze', '브론즈 → 골드'), ('gold', '골드 → 다이아몬드')], db_index=True, max_length=10, verbose_name='출발 티어'),
        ),
        migrations.AlterField(
            model_name='promotionexam',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
